<?php 
$status = session_status();
if($status == PHP_SESSION_NONE){
    //There is no active session
    session_start();
}
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Application Status</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    </head>
	<body>
	
    
    <div id="bground">
    <div class="container" id="divcontainer" style="margin-top:100px; padding-bottom:25px;">
    <?php 
    include 'php/window.php';
    include 'php/functions.php';
    $db = db_connect();
    $window = searchForWindow($db);
    if(empty($window)){
        echo "no time window";
    }
    
    elseif (strcmp($window, "apply") == 0){
       if(isset($_SESSION['username'])){
            $appSubmitted = pg_query($db, "SELECT app_submitted FROM applicant WHERE sso = '".$_SESSION['username']."'");
            if(pg_fetch_array($appSubmitted)[0] == TRUE){
               
                echo "<div style='text-align:center; font-size:20pt; margin-top:100px;'>";
                   echo "Your application has been submitted and is pending review.";
                   echo "</div>";
            }
            else {
                echo "<div style='text-align:center; font-size:20pt; margin-top:100px;'>";
                echo "You have not yet submitted an application";
                echo "</div>";
            }
        }
    }
    
    elseif (strcmp($window, "selection") == 0){
        if(isset($_SESSION['username'])){
            $getOffer = pg_query($db, "SELECT * FROM applicant_offer_received WHERE sso = '".$_SESSION['username']."' AND offer_accepted IS NULL AND assigned_to_course IS NULL");
            if($getOffer != NULL){
                while (($row = pg_fetch_assoc($getOffer))){
                    echo "<div style='text-align:center; font-size:20pt; margin-top:100px;'>";
                    echo "You have been selected as an assistant for ". $row['course_id'];
                    echo "</div>";
                    echo "<form action='' method='POST'><button type='submit' class='btn btn-primary' name='acceptOffer' style='margin-left:475px; margin-right:20px; margin-top:20px;'>Accept</button><button type='submit' class='btn btn-danger'' name='rejectOffer' style='margin-top:20px;'>Reject</button><input type='hidden' name='course_id' value='" . $row['course_id'] . "'></form>";
                }
            }
            else {
                echo "Your application under review.  Please check back later.";
            }
        }
        
        if(isset($_POST['acceptOffer'])){
            pg_query($db, "UPDATE applicant_offer_received SET offer_accepted=TRUE WHERE sso = '".$_SESSION['username']."' AND course_id = '".$_POST['course_id'] ."';");
            echo "<p style='text-align:center;'>Thank you for your response.</p>";
        }
        
        if(isset($_POST['rejectOffer'])){
            pg_query($db, "UPDATE applicant_offer_received SET offer_accepted=FALSE WHERE sso = '".$_SESSION['username']."' AND course_id = '".$_POST['course_id'] ."';");
        }
      }
    
    elseif (strcmp($window, "accept") == 0){
        if(isset($_SESSION['username'])) {
            $assigned = pg_query($db, "SELECT * FROM applicant_offer_received WHERE sso = '".$_SESSION['username']."' AND offer_accepted IS TRUE AND assigned_to_course IS TRUE");
            if(pg_num_rows($assigned) >= 1){
                echo "<div style='text-align:center; font-size:20pt; margin-top:100px;'>";
                while(($results = pg_fetch_assoc($assigned))){
                    echo "Congratulations! You have been assigned to course ". $results['course_id']." for the upcoming semester.";
                }
            }
            else  {
                echo "<div style='text-align:center; font-size:20pt; margin-top:100px;'>";
                echo "All positions have been filled for this semester.  Please apply again next semster.";
            }
        }
    }
  
    ?>
    
        <div id="application_time"></div>
        
        <div id="offer_time"></div>
        <div id="notice_time"></div>
    </div>
    </div>
    
    
    <footer class="text-center"> Copyright &copy; Software Engineering Group H, Spring 201</footer>

    <script>
//     $(document).ready(function() {
//           var height=$('#divcontainer').height();
//           height+=30;
//           $('divcontainer').height(height);
//         });
   
    </script>


  
	<!-- script references 
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>-->
		
	</body>
</html>