<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Application Status</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    </head>
	<body>
	<nav class="navbar navbar-inverse navbar-fixed-top navbars" role="navigation">
		<img id="images" src="http://web.missouri.edu/~sykutam/images/mizzou_logo.gif" alt="tigermark" href="http://missouri.edu/">
        <div class="container" id="contain">
            <!-- Brand and toggle get grouped for better mobile display -->
			
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				
            
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/swespring2015">Home</a>
                    </li>
                    <li>
                        <a href="login">Login</a>
                    </li>
                    <li>
                        <a href="applicationform">Application Form</a>
                    </li>
                    <li>
                        <a href="studentpage">Student page</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
					<a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
						<i class="glyphicon glyphicon-user"></i> 
						<?php 
						if(isset($_SESSION['username'])){
    						echo $_SESSION["username"];
						}
						else {
						    echo "";
						}
						?> 
						<span class="caret"></span></a>
					<ul id="g-account-menu" class="dropdown-menu" role="menu">
						<li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
						<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
					</ul>
				</ul>
				</ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    
    <div id="bground">
    <div class="container">
        <div id="application_time"></div>
        <div id="offer_time"></div>
        <div id="notice_tiem"></div>
    </div>
    </div>
    
    
    <footer class="text-center"> Copyright &copy; Software Engineering Group H, Spring 201</footer>




  
	<!-- script references 
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>-->
	</body>
</html>