<?php 
use Studentpage\Module;
session_start();


?>
<!-- <nav class="navbar navbar-inverse navbar-fixed-top navbars" role="navigation"> -->
<!-- 		<img id="images" src="http://web.missouri.edu/~sykutam/images/mizzou_logo.gif" alt="tigermark" href="http://missouri.edu/"> -->
<!--         <div class="container" id="contain"> -->
            <!-- Brand and toggle get grouped for better mobile display -->
			
<!--             <div class="navbar-header"> -->
<!--                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> -->
<!--                     <span class="sr-only">Toggle navigation</span> -->
<!--                     <span class="icon-bar"></span> -->
<!--                     <span class="icon-bar"></span> -->
<!--                     <span class="icon-bar"></span> -->
<!--                 </button> -->
				
            
<!--             </div> -->
            <!-- Collect the nav links, forms, and other content for toggling -->
<!--             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
<!--                 <ul class="nav navbar-nav"> -->
<!--                     <li> -->
<!--                         <a href="/swespring2015">Home</a> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                         <a href="login">Login</a> -->
<!--                     </li> -->
<!--                 </ul> -->
<!--                 <ul class="nav navbar-nav navbar-right"> -->
<!-- 					<li class="dropdown"> -->
<!-- 					<a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"> -->
<!-- 						<i class="glyphicon glyphicon-user"></i>  -->
						<?php 
// 						if(isset($_SESSION['username'])){
//     						echo $_SESSION["username"];
// 						}
// 						else {
// 						    echo "";
// 						}
						?> 
<!-- 						<span class="caret"></span></a> -->
<!-- 					<ul id="g-account-menu" class="dropdown-menu" role="menu"> -->
<!-- 						<li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li> -->
<!-- 						<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li> -->
<!-- 					</ul> -->
<!-- 				</ul> -->
<!-- 				</ul> -->
<!--             </div> -->
            <!-- /.navbar-collapse -->
<!--         </div> -->
        <!-- /.container -->
<!--     </nav> -->

<div style="width:300px; height:300px; margin-left:auto; margin-right:auto; margin-top:100px; background-color:#E0E0EB; border-radius:12px;">
    <form id='login' action=' ' method='post' accept-charset='UTF-8'>
        <fieldset style="text-align:center;" >
        <legend style="font-size: 25pt;">Login</legend>
        <input type='hidden' name='submitted' id='submitted' value='1'/>
         
        <label for='username' >PawPrint:</label>
        <input type='text' name='pawprint' id='pawprint'  maxlength="50" />
        <br>
        <br>
        <label for='password' >Password:</label>
        <input type='password' name='password' id='password' maxlength="50" />
        <br>
        <br>
        <button type='submit' class="btn btn-primary" name='login'/>Login</button>
        </fieldset>
    </form>
</div>

<!-- Footer -->
    <footer style="position:fixed; bottom:0; margin-left:450px;">
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Software Engineering Group H, Spring 2015</p>
            </div>
        </div>
    </footer>
    
    <?php 
    if(isset($_POST['login']))
    {
        Login();
    }
    
    function Login()
    {
        if(empty($_POST['pawprint']))
        {
            echo "<br>password is empty!";
            return false;
        }
         
        if(empty($_POST['password']))
        {
            echo "<br>password is empty!";
            return false;
        }
         
        $pawprint = trim($_POST['pawprint']);
        $password = trim($_POST['password']);
        //$_SESSION['username'] = $pawprint;
         
        if(!CheckLoginInDB($pawprint,$password))
        {
            
        }
        echo "<br>YOU HAVE LOGGED IN!";
        
    }
    
    function CheckLoginInDB($pawprint,$password)
    {
        
        
        require "php/functions.php";
        $DBconn = db_connect();
        require "php/authentication.php";
        $results = authenticate($pawprint, $password, $DBconn);
        echo "<br>" . $results['error'];
        if($results['error'] == 1)
        {
            echo "<p>Incorrect username or password</p>";
            return false;
        }
        else if($results['error'] == 2)
        {
            echo "<p>Unauthorized Access</p>";
        }
        else if($results['error'] == 0){
           echo $results['type'];
           if(strcmp($results['type'], "instructor") == 0){
               $_SESSION['username'] = $pawprint;
               $_SESSION['status']= "instructor";
               header('Location:professorpage');
               exit;
            }
            
            else if(strcmp($results['type'], "applicant") == 0){
                $_SESSION['username'] = $pawprint;
                $_SESSION['status']= "applicant";
                header('Location:studentpage');
                exit;
            }
            else if(strcmp($results['type'], "admin") == 0){
                $_SESSION['username'] = $pawprint;
                $_SESSION['status']= "admin";
                header('Location:admin');
                exit;
            }
            else if(strcmp($results['type'], "new") == 0){
                $_SESSION['username'] = $pawprint;
                $_SESSION['status']= "new";
                header('Location:studentpage');
                exit;
            }
        }
    }
    ?>
  
<!-- jQuery -->
<!-- Bootstrap Core JavaScript -->
	