<div style="width:300px; margin-left:auto; margin-right:auto; margin-top:200px;">
    <form id='login' action='' method='post' accept-charset='UTF-8'>
        <fieldset style="text-align:center;" >
        <legend>Login</legend>
        <input type='hidden' name='submitted' id='submitted' value='1'/>
         
        <label for='username' >PawPrint:</label>
        <input type='text' name='pawprint' id='pawprint'  maxlength="50" />
        <br>
        <br>
        <label for='password' >Password:</label>
        <input type='password' name='password' id='password' maxlength="50" />
        <br>
        <br>
        <input type='submit' name='login' value='Login' />
        </fieldset>
    </form>
</div>

<!-- Footer -->
    <footer style="position:fixed; bottom:0; margin-left:450px;">
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Software Engineering Group H, Spring 2015</p>
            </div>
        </div>
    </footer>
    
    <?php 
    if(isset($_POST['login']))
    {
        Login();
    }
    
    function Login()
    {
        if(empty($_POST['pawprint']))
        {
            echo "<br>password is empty!";
            return false;
        }
         
        if(empty($_POST['password']))
        {
            echo "<br>password is empty!";
            return false;
        }
         
        $pawprint = trim($_POST['pawprint']);
        $password = trim($_POST['password']);
         
        if(!CheckLoginInDB($pawprint,$password))
        {
            
        }

        echo "<br>YOU HAVE LOGGED IN!";
        
    }
    
    function CheckLoginInDB($pawprint,$password)
    {
        
        require "php/functions.php";
        $DBconn = db_connect();
        require "php/authentication.php";
        $results = authenticate($pawprint, $password, $DBconn);
        echo "<br>" . $results['error'];
        if($results['error'] == 1)
        {
            echo "<p>Incorrect username or password</p>";
            return false;
        }
        else if($results['error'] == 2)
        {
            echo "<p>Unauthorized Access</p>";
        }
        else if($results['error'] == 0){
           echo $results['type'];
           if(strcmp($results['type'], "instructor") == 0){
                echo "professorpage";
            }
            else if(strcmp($results['type'], "applicant") == 0){
                echo"studentpage";
            }
            else if(strcmp($results['type'], "admin") == 0){
                echo"adminpage";
            }
            else if(strcmp($results['type'], "new") == 0){
                echo"adminpage";
            }
            $_SESSION['username'] = $pawprint;
            session_name("WebApplication");
            session_start();
        }
    }
    
    ?>

<!-- jQuery -->
<!-- Bootstrap Core JavaScript -->
	