<?php 
$status = session_status();
if($status == PHP_SESSION_NONE){ header("Location:Login"); }
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>

    
    
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>Application Form</title>
	 <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/swe-style.css')
	           ->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css')
	           ->prependStylesheet($this->basePath().'/css/jquery.signaturepad.css');
    ?>
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/js/jquery.inputfocus-0.9.min.js')
        ->prependFile($this->basePath() . '/js/jquery-applicationForm.js')
        ->prependFile($this->basePath() . '/js/jquery.signaturepad.js')
        ->prependFile($this->basePath() . '/js/json2.min.js')
        ->prependFile('//code.jquery.com/ui/1.11.4/jquery-ui.js')
        ->prependFile('//code.jquery.com/jquery-1.10.2.js');
    
    
         ?>   
 
</head>
<body>
    
<div id="container">
        <form action="save_stu_app.php" method="post">
    
            <!-- #first_step -->
            <div id="first_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>

                <div class="form">

                    <select name="selection" id="selection" value="selection" >
                    <option value="TA">TA (grad student)</option>
                    <option value="PLA">PLA (undergrad student)</option>
      
                    </select>
                    
                    <input type="text" name="fname" id="fname" value="fname" />
                    <label for="fname">Please enter your first name.</label>
                    
                    <input type="text" name="lname" id="lname" value="lname" />
                    <label for="lname">Please enter your last name.</label>

                    <input type="text" name="gpa" id="gpa" value="gpa" />
                    <label for="gpa" id='label_gpa'>Please enter your GPA.</label>



<!-- Testing !-->
                
<br>

                    <br/>
                


                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->

     
                <input class="submit" type="submit" name="submit_first" id="submit_first" value="" />
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->


             <!--  
            <div id="temp_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                
               <form method="post" name="Profile" enctype="multipart&#x2F;form-data" action="&#x2F;swespring2015&#x2F;applicationform" id="Profile">
               
               <input name="profilename" type="text" value="">
               <label for="profilename">profile name:</label>
               
               <input name="fileupload" type="file">
               <label for="fileupload">File Upload </label>
               <input name="submit" type="submit" value="Upload&#x20;Now">
               </form>            
               <hr>
               
                                    
               <input class="submit" type="submit" name="submit_temp" id="submit_temp" value="" />
                
            </div>      <div class="clear"></div>
             -->
            <!-- #second_step -->
            <div id="second_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>

                <div class="form">
                <!--<input type="text" name="ID" id="ID" value="stu ID" />  Had to change this to the right name-->
                    <input type="text" name="pub" id="ID" value="stu ID" />
                    <label for="ID">Your student ID. </label>

                    
                    
                    <input type="text" name="advisorname" id="advisorname" value="advisor name" />
                    <label for="advisorname" id="label_advisor">Your advisor name</label>
                    
                    <select name="masterphd" id="masterphd" value="masterphd" >
                    <option value="default">choose one..</option>
                    <option value="master">master</option>
                    <option value="phd">phd</option> 
                 
                        
                    </select>

                    <select name="selectionmajor" id="selectionmajor" value="selectionmajor" >
                    <option value="BSIT">BS IT</option>
                    <option value="BACS">BA CS</option> 
                    <option value="BAIT">BA IT</option> 
                    <option value="BSCS">BS CS</option> 
                    <option value="other">other</option> 
                        
                    </select>
                    <label for="selectionmajor" id="label_selectmajor">Select your major</label>
                    <br>
                    
 <!--                  
                    
                    <input type="text" name="source" id="source" value="enter the full info" />
                    <label for="source">If undergraduate applying for PLA, indicate program and level (ex.CS BA jr). If graduate, please enter advisor name. </label>
                    
                    
             -->          
                    <input type="text" name="pub" id="email" value="email address" />
                    <label for="email">Your email address. We send important administration notices to this address. </label>                    
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->


                <input class="submit_back" type="submit" name="submit_second_back" id="submit_second_back" value="" />
            
                <input class="submit" type="submit" name="submit_second" id="submit_second" value="" />
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->


            <!-- #third_step -->
            <div id="third_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <input type="text" name="phoneNum" id="phoneNum" value="phone number" />
                    <label for="phoneNum">Your phone number. </label>



                    <p> <input type="text" name="gradDate" id="gradDate" value="graduate date">
                        <label for="gradDate">Please enter your graduation date.</label>
                    </p>
                    <input type="text" name="currCourses" id="currCourses" value="current teaching courses" />
                    <label for="currCourses">Course(s) You Are Currently Teaching </label>                    
           
                             
                    

                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                <input class="submit_back" type="submit" name="submit_third_back" id="submit_third_back" value="" />
                
                <input class="submit" type="submit" name="submit_third" id="submit_third" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
            
            <!-- #fourth_step -->
            <div id="fourth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <input type="text" name="precourse" id="precourse" value="Previously Taught" />
                    <label for="precourse">Course(s) You Have Previously Taught: </label>

                    <table id="buttontable"><tbody>
                        <tr>
                            <td>
                                <input type="button" id="btAdd" name="btset" value="Click it to start" class="bt" />
                            </td>

                            <td>
                                 <input type="button" id="btRemove" name="btset" value="Remove a Course" class="bt" />
                            </td>
                        </tr>
                    </tbody></table>
                    
                    

                    <input type="text" name="otherPlace" id="otherPlace" value="other place" />
                    <label for="otherPlace">Other Places You Work:</label>                    
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                <input class="submit_back" type="submit" name="submit_fourth_back" id="submit_fourth_back" value="" />
            
                <input class="submit" type="submit" name="submit_fourth" id="submit_fourth" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
           <!-- #fifth_step destoryed-->
           
           <!-- 
            <div id="fifth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <input type="text" name="speakScore" id="speakScore" value="speak score" />
                    <label for="speakScore">SPEAK/OPT score, if applicable</label>
                    <p><input type="text" name="semesterLast" id="semesterLast" value="enter the semster" /></p>
                    <label for="semesterLast">Time of last test</label>
                    
                   
                </div>     <div class="clear"></div>   
                    
                <input class="submit" type="submit" name="submit_fifth" id="submit_fifth" value="" />
                
            </div>      <div class="clear"></div>
           -->
             <!-- #sixth_step -->
            <div id="sixth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <li class="note">Please list the courses that you’d like to be a TA for</li>
                    <br>
                    <li class="note">Per CS Dept. policy, GTA’s must not exceed half-time total employmentwithin the University system including, but not limited to, the CS department.</li>
                    <br>
                     <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.) </li>
                     <select name="selectiontwo" id="selectiontwo" value="selectiontwo" >
                    <option value="rm">Requirement met</option>
                    <option value="will attend">Will attend in Aug./Jan. (if selected)</option>
                    </select>
                    <br>
                    <select name="selectionifinternational" id="selectionifinternational" value="selectionifinternational" >
                    <option value="default">Are you international student?</option>
                    
                    <option value="yes">yes</option>
                    <option value="no">no</option>
                    </select>
                    
                    
                    <br>


                 
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                <input class="submit_back" type="submit" name="submit_sixth_back" id="submit_sixth_back" value="" />
            
                <input class="submit" type="submit" name="submit_sixth" id="submit_sixth" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
           

            <!-- #seventh_step -->
            <div id="seventh_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <li class="note">INTERNATIONAL STUDENTS, PLEASE BE AWARE OF THE FOLLOWING:</li>
                    <br>
                    <li class="note">Prior to becoming a TA, any ITA (International Teaching Assistant) who received their primary and secondary education in a country where English is not the principal language are required by law to be assessed for English proficiency (SPEAK test). If you do not register for and satisfy applicable language assessment requirements, you will not be eligible to accept a TA appointment. Arrangements for language assessments must be made before the end of the semester prior to accepting a TA position.</li>
                    <br>
                     <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.) </li>
                      <li class="note">A potential ITA is required to have satisfactorily completed at least one semester as a student at the University of Missouri before being considered for a TA position.</li>

                     
                     
                     <select name="selectionthree" id="selectionthree" value="selectionthree" >
                    <option value="default">Choose one...</option>
                    <option value="rm">Requirement met</option>
                    <option value="register">Registered for SPEAK (date)</option>
                    </select>
                    
               <!-- Had to changed sub1 to sub1, sub2, sub3: ZDC9PD -->
                     <input type="text" name="sub1" id="speakScore" value="speak score" />
                    <label for="speakScore">SPEAK/OPT score, if applicable</label>
                    <p><input type="text" name="sub1" id="semesterLast" value="enter the semster" /></p>
                    <label for="semesterLast">Time of last test</label>
                    <p><input type="text" name="sub2" id="timetoregister" value="enter the time" /></p>
                    <label for="timetoregister" id="labelregister">Time to register</label>
                    


                    <br>
                   
                 
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                <input class="submit_back" type="submit" name="submit_seventh_back" id="submit_seventh_back" value="" />
            
                <input class="submit" type="submit" name="submit_seventh" id="submit_seventh" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
           

           <!-- #eighth_step -->
           <div id="eighth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                   
                    <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.)</li>
                    <br>
                     <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.) </li>
                      <select name="selectionfour" id="selectionfour" value="selectionfour" >
                     <option value="rm">Requirement met</option>
                     <option value="will attend">Will attend in Aug./Jan. (if selected)</option>
                     </select>

                     <li class="note">ONITA, is a requirement for all international TAs and PLAs who have not previously attended this orientation. You cannot have a TA/PLA appointment until this requirement has been met. (You do not need to attend more than once.) </li>
                     

                    <br>
                    <li class="note">A potential ITA is required to have satisfactorily completed at least one semester as a student at the University of Missouri before being considered for a TA position.</li>

                    <select name="selectionfive" id="selectionfive" value="selectionfive" >
                    <option value="rm">Requirement met</option>
                    <option value="will attend">Will attend in Aug./Jan. (if selected)</option>
                    </select>

                 
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                <input class="submit_back" type="submit" name="submit_eighth_back" id="submit_eighth_back" value="" />
            
                <input class="submit" type="submit" name="submit_eighth" id="submit_eighth" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
            <!-- #xxth_step -->
            <div id="ninth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>

                <div class="form">
                    <h2>Summary</h2>
                    
          
                    <table>
                        <tr><td>TA? PLA?</td><td></td></tr>
                        <tr><td>Name</td><td></td></tr>
                        <tr><td>GPA</td><td></td></tr>
                        <tr><td>Stu ID</td><td></td></tr>
                        <tr><td>Program and level</td><td></td></tr>
                        <tr><td>Email</td><td></td></tr>
                        <tr><td>Phone number</td><td></td></tr>
                        <tr><td>Graduation Date</td><td></td></tr>
                        <tr><td>Current teaching Courses</td><td></td></tr>
                        <tr><td>Previous teaching courses</td><td></td></tr>
                        <tr><td>Course you would lke to teach and grade</td><td></td></tr>
                        <tr><td>Other place you work</td><td></td></tr>
                        <tr><td>Speak score</td><td></td></tr>
                        <tr><td>Semester of last test</td><td></td></tr>
                    </table>
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
                <input class="submit_back" type="submit" name="submit_ninth_back" id="submit_ninth_back" value="" />
            
                <input class="submit" type="submit" name="submit_ninth" id="submit_ninth" value="" />            
            </div>

            <!-- #third_step -->
            <div id="sign_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>GRADUATE TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <iframe src="http://dslsrv8.cs.missouri.edu/~zzff8/applicationForm/test.html">
                      <p>Your browser does not support iframes.</p>
                    </iframe>

                    <br>
                    <p> <input type="text" name="presentDate" id="presentDate" value="Date">
                        <label for="presentDate">Date</label>
                    </p>
                   
                    
                </div>
                     <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                <input class="submit_back" type="submit" name="submit_sign_back" id="submit_sign_back" value="" />
                
                <input class="submit" type="submit" name="submit_sign" id="submit_sign" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
            
</div> 
            
        </form>
    </div>
    <div id="progress_bar">
        <div id="progress"></div>
        <div id="progress_text">0% Complete</div>
    </div>
    
</body>
</html>
