<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>

	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>Application Form</title>
	 <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/swe-style.css')
	           ->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
    ?>
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/js/jquery.inputfocus-0.9.min.js')
        ->prependFile($this->basePath() . '/js/jquery-applicationForm.js')
        
        ->prependFile('//code.jquery.com/ui/1.11.4/jquery-ui.js')
        ->prependFile('//code.jquery.com/jquery-1.10.2.js');
    
    
         ?>   
 
</head>
<body>
	
<div id="container">
        <form action="#" method="post">
	
            <!-- #first_step -->
            <div id="first_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>

                <div class="form">

                    <select name="selection" id="selection" value="selection" placeholder="Please Select" >
                    <option value="TA">TA (grad student)</option>
                    <option value="PLA">PLA (undergrad student)</option>
      
                    </select>
                    <input type="text" name="name" id="name" value="name" />
                    <label for="name">Please enter your full name.</label>

                    <input type="text" name="gpa" id="gpa" value="gpa" />
                    <label for="gpa">Please enter your GPA.</label>
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
                <input class="submit" type="submit" name="submit_first" id="submit_first" value="" />
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->


            <!-- #second_step -->
            <div id="second_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>

                <div class="form">
                    <input type="text" name="ID" id="ID" value="stu ID" />
                    <label for="ID">Your student ID. </label>

                    <input type="text" name="source" id="source" value="enter the full info" />
                    <label for="source">If undergraduate applying for PLA, indicate program and level (ex.CS BA jr). If graduate, please enter advisor name. </label>
                    <input type="text" name="email" id="email" value="email address" />
                    <label for="email">Your email address. We send important administration notices to this address. </label>                    
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
                <input class="submit" type="submit" name="submit_second" id="submit_second" value="" />
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->


            <!-- #third_step -->
            <div id="third_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <input type="text" name="phoneNum" id="phoneNum" value="phone number" />
                    <label for="phoneNum">Your phone number. </label>



                    <p> <input type="text" name="gradDate" id="gradDate" value="graduate date"></p>
                    <label for="gradDate">Please enter your graduation date.</label>




                    <input type="text" name="currCourses" id="currCourses" value="current teaching courses" />
                    <label for="currCourses">Course(s) You Are Currently Teaching </label>                    
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                    
                <input class="submit" type="submit" name="submit_third" id="submit_third" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
            
            <!-- #fourth_step -->
            <div id="fourth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <input type="text" name="precourse" id="precourse" value="Previously Taught" />
                    <label for="precourse">Course(s) You Have Previously Taught: </label>

                    <input type="text" name="courseLike" id="courseLike" value="Course you would like and grade" />
                    <label for="courseLike">Course(s) You Would Like to Teach (must have taken previously), include grades received:</label>
                    <input type="text" name="otherPlace" id="otherPlace" value="other place" />
                    <label for="otherPlace">Other Places You Work:</label>                    
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                    
                <input class="submit" type="submit" name="submit_fourth" id="submit_fourth" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
           <!-- #fifth_step -->
            <div id="fifth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <input type="text" name="speakScore" id="speakScore" value="speak score" />
                    <label for="speakScore">SPEAK/OPT score, if applicable</label>
                    <p><input type="text" name="semesterLast" id="semesterLast" value="enter the semster" /></p>
                    <label for="semesterLast">Time of last test</label>
                    
                   
                 
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                    
                <input class="submit" type="submit" name="submit_fifth" id="submit_fifth" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
             

             <!-- #sixth_step -->
            <div id="sixth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <li class="note">Please list the courses that you’d like to be a TA for</li>
                    <br>
                    <li class="note">Per CS Dept. policy, GTA’s must not exceed half-time total employmentwithin the University system including, but not limited to, the CS department.</li>
                    <br>
                     <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.) </li>
                     <select name="selectiontwo" id="selectiontwo" value="selectiontwo" >
                    <option value="rm">Requirement met</option>
                    <option value="will attend">Will attend in Aug./Jan. (if selected)</option>
                    </select>
                    <br>
                    <li class="note">Please return this form to 244 EBW along with a current resume!</li>


                 
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                    
                <input class="submit" type="submit" name="submit_sixth" id="submit_sixth" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
           

            <!-- #seventh_step -->
            <div id="seventh_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                    <li class="note">INTERNATIONAL STUDENTS, PLEASE BE AWARE OF THE FOLLOWING:</li>
                    <br>
                    <li class="note">Prior to becoming a TA, any ITA (International Teaching Assistant) who received their primary and secondary education in a country where English is not the principal language are required by law to be assessed for English proficiency (SPEAK test). If you do not register for and satisfy applicable language assessment requirements, you will not be eligible to accept a TA appointment. Arrangements for language assessments must be made before the end of the semester prior to accepting a TA position.</li>
                    <br>
                     <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.) </li>
                     <select name="selectionthree" id="selectionthree" value="selectionthree" >
                    <option value="rm">Requirement met</option>
                    <option value="register">Registered for SPEAK (date)</option>
                    </select>

                    <br>
                    <li class="note">A potential ITA is required to have satisfactorily completed at least one semester as a student at the University of Missouri before being considered for a TA position.</li>


                 
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                    
                <input class="submit" type="submit" name="submit_seventh" id="submit_seventh" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
           

           <!-- #eighth_step -->
           <div id="eighth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>
                <div class="form">
                   
                    <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.)</li>
                    <br>
                     <li class="note">New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO (Graduate Assistant Teaching Orientation), which is offered just prior to the start of fall and winter terms. (You do not need to attend more than once.) </li>
                      <select name="selectionfour" id="selectionfour" value="selectionfour" >
                     <option value="rm">Requirement met</option>
                     <option value="will attend">Will attend in Aug./Jan. (if selected)</option>
                     </select>

                     <li class="note">ONITA, is a requirement for all international TAs and PLAs who have not previously attended this orientation. You cannot have a TA/PLA appointment until this requirement has been met. (You do not need to attend more than once.) </li>
                     

                    <br>
                    <li class="note">A potential ITA is required to have satisfactorily completed at least one semester as a student at the University of Missouri before being considered for a TA position.</li>

                    <select name="selectionfive" id="selectionfive" value="selectionfive" >
                    <option value="rm">Requirement met</option>
                    <option value="will attend">Will attend in Aug./Jan. (if selected)</option>
                    </select>

                 
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->     
                    
                <input class="submit" type="submit" name="submit_eighth" id="submit_eighth" value="" />
                
            </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
            <!-- #xxth_step -->
            <div id="ninth_step">
                <h1>COMPUTER SCIENCE DEPARTMENT<br> <span>TEACHING ASSISTANT APPLICATION</span> </h1>

                <div class="form">
                    <h2>Summary</h2>
                    
          
                    <table>
                        <tr><td>TA? PLA?</td><td></td></tr>
                        <tr><td>Name</td><td></td></tr>
                        <tr><td>GPA</td><td></td></tr>
                        <tr><td>Stu ID</td><td></td></tr>
                        <tr><td>Program and level</td><td></td></tr>
                        <tr><td>Email</td><td></td></tr>
                        <tr><td>Phone number</td><td></td></tr>
                        <tr><td>Graduation Date</td><td></td></tr>
                        <tr><td>Current teaching Courses</td><td></td></tr>
                        <tr><td>Previous teaching courses</td><td></td></tr>
                        <tr><td>Course you would lke to teach and grade</td><td></td></tr>
                        <tr><td>Other place you work</td><td></td></tr>
                        <tr><td>Speak score</td><td></td></tr>
                        <tr><td>Semester of last test</td><td></td></tr>
                    </table>
                </div>      <!-- clearfix --><div class="clear"></div><!-- /clearfix -->
                <input class="send submit" type="submit" name="submit_ninth" id="submit_ninth" value="" />            
            </div>
            
        </form>
	</div>
	<div id="progress_bar">
        <div id="progress"></div>
        <div id="progress_text">0% Complete</div>
	</div>
	
</body>
</html>
