<?php
$status = session_status();
if($status == PHP_SESSION_NONE) { header("Location:Login"); }
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Student Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    </head>
	<body>
	<nav class="navbar navbar-inverse navbar-fixed-top navbars" role="navigation">
		<img id="images" src="http://web.missouri.edu/~sykutam/images/mizzou_logo.gif" alt="tigermark" href="http://missouri.edu/">
        <div class="container" id="contain">
            <!-- Brand and toggle get grouped for better mobile display -->
			
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				
            
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
<!--             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
<!--                 <ul class="nav navbar-nav"> -->
<!--                     <li> -->
<!--                         <a href="/swespring2015">Home</a> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                         <a href="login">Login</a> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                         <a href="applicationform">Application Form</a> -->
<!--                     </li> -->
<!--                     <li> -->
<!--                         <a href="studentpage">Student page</a> -->
<!--                     </li> -->
<!--                 </ul> -->
<!--                 <ul class="nav navbar-nav navbar-right"> -->
<!-- 					<li class="dropdown"> -->
<!-- 					<a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"> -->
<!-- 						<i class="glyphicon glyphicon-user"></i>  -->
						<?php 
// 						if(isset($_SESSION['username'])){
//     						echo $_SESSION["username"];
// 						}
// 						else {
// 						    echo "";
// 						}
						?> 
<!-- 						<span class="caret"></span></a> -->
<!-- 					<ul id="g-account-menu" class="dropdown-menu" role="menu"> -->
<!-- 						<li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li> -->
<!-- 						<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li> -->
<!-- 					</ul> -->
<!-- 				</ul> -->
<!-- 				</ul> -->
<!--             </div> -->
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
	<div id="bground" style="margin-top: 50px; border-radius:12px;">
    <div class="container">
        <!-- First Featurette -->
        <div class="featurette1" >
			
            <h5 class="featurette-heading">Application Instructions</h5>
            <div class="lead">
				<li>Click the link below to being filling out the Application Form.</li>
				<li>Only one application is needed per applicant</li>
				<li>All applications must be submitted by the deadline - April 3, 2015</li>
				<li>To view the status of your application, use the "View Application Status" button below.</li>
			</div>
			<div>
			     <form action="applicationform" method="POST"><button class="btn btn-success">Start Application</button></form>
			</div>
			<div style="margin-top: -33px; margin-left:175px;">
			     <form action="applicationstatus" method="POST">
    			     <input type="hidden" name="username" value="<?echo $_SESSION['username']?>"></input>
    			     <button class="btn btn-info">View Application Status</button>
			     </form>	
		    </div>
    </div>



        <!-- Footer -->
        <footer style="text-align: center;">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Software Engineering Group H, Spring 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
	</div>

	   
</body>

</html>
