<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Student Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		
        
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
	<div id="bground">
    <div class="container">
		<div class="startApp">
			<button class="btn btn-info btn-large" href="#">Start Application Form Now</button>
		</div>
        <!-- First Featurette -->
        <div class="featurette1" >
			
            <h5 class="featurette-heading">Application Instruction</h5>
            <div class="lead">
				<li>Begin filling the Application Form.</li>
				<li>Submit before Deadline: Friday, April 3nd.</li>
				<li>Need specific information like GPA.</li>
			</div>
        </div>



        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Software Engineering Group H, Spring 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
	</div>

	   
</body>

</html>