<?php
session_start();
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Student Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    </head>
	<body>

						
	<div id="bground" style="margin-top: 50px; border-radius:12px;">
    <div class="container">
        <!-- First Featurette -->
        <div class="featurette1" >
			
            <h5 class="featurette-heading">Application Instructions</h5>
            <div class="lead">
				<li>Click the link below to being filling out the Application Form.</li>
				<li>Only one application is needed per applicant</li>
				<li>All applications must be submitted by the deadline - April 3, 2015</li>
				<li>To view the status of your application, use the "View Application Status" button below.</li>
			</div>
			<div>
			     <form action="test" method="POST"><button class="btn btn-success">Start Application</button></form>
			</div>
			<div style="margin-top: -33px; margin-left:175px;">
			     <form action="applicationstatus" method="POST">
    			     <input type="hidden" name="username" value="<?echo $_SESSION['username']?>"></input>
    			     <button class="btn btn-info">View Application Status</button>
			     </form>	
		    </div>
    </div>



        <!-- Footer -->
        <footer style="text-align: center;">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Software Engineering Group H, Spring 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
	</div>

	   
</body>

</html>
