<?php 
$form = $this->form;
$form->setAttribute('action',
                    $this->url('test', //your route name ...
                               array('controller'=>'test', 'action' => 'index'))); 
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formRow($form->get('profilename'));
 
echo $this->formRow($form->get('fileupload'));
 
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>