<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Testing\Module'                        => __DIR__ . '/Module.php',
    'Testing\Controller\TestingController' => __DIR__ . '/src/Testing/Controller/TestingController.php',
    'TestingTest\Framework\TestCase'        => __DIR__ . '/tests/Testing/Framework/TestCase.php',
    'TestingTest\SampleTest'                => __DIR__ . '/tests/Testing/SampleTest.php',
);
