<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Applicationform\Module'                        => __DIR__ . '/Module.php',
    'Applicationform\Controller\ApplicationformController' => __DIR__ . '/src/Applicationform/Controller/ApplicationformController.php',
    'ApplicationformTest\Framework\TestCase'        => __DIR__ . '/tests/Applicationform/Framework/TestCase.php',
    'ApplicationformTest\SampleTest'                => __DIR__ . '/tests/Applicationform/SampleTest.php',
);
