<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Admin Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/prof_styles.css')
    ?>
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
<!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button>
      <a class="navbar-brand" href="#">TA/PLA Application For Admin</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
            <i class="glyphicon glyphicon-user"></i> Admin: Dove <span class="caret"></span></a>
          <ul id="g-account-menu" class="dropdown-menu" role="menu">
            <li><a href="#">My Profile</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  <div class="row">
	<div class="col-sm-3">
      <!-- left -->
      <h3><i class="glyphicon glyphicon-briefcase"></i> Toolbox</h3>
      
      <ul class="nav nav-stacked">
		<li><a href="#rankta"> Rank TA</a></li>
        <li><a href="#addcourse"> Add Courses</a></li>
        <li><a href="#deletecourse"> Delete Courses</a></li>
        <li><a href="javascript:;"> Assign TA</a></li>
      </ul>
      
      <hr>
      
  	</div><!-- /span-3 -->
    
    <div class="col-md-6" style="margin-top: 40px;">
       <div class="well">
            <h3>Search for an Applicant</h3>
            <form>
                <input type="radio" name="choice" value="pawprint">Search by PawPrint
                <br>
                <input type="radio" name="choice" value="name">Search by Applicant Name
                <br>
                <input type="text" name="input">
                <input type="submit" value="Submit">
            </form>
       </div>
     </div>
    
  </div><!--/row-->
  <!-- /upper section -->
  
  
  <!-- lower section -->
  <div class="row">
    
    <div class="col-md-12" id="rankta">
    
     <h4><strong><i class="glyphicon glyphicon-list-alt"></i> Application Forms</strong></h4>
         
    
      <table class="table table-striped">
        <thead>
          <tr><th>Applicants</th><th>Course</th><th>TA/PLA</th><th>Add Rank</th></tr>
        </thead>
        <tbody>
          <tr><td>Sam Walker</td><td>CS4320</td><td>TA</td><td>92</td></tr>
          <tr><td>Tory White</td><td>CS4320</td><td>TA</td><td>94</td></tr>
          <tr><td>Tylor </td><td>CS4320</td><td>PLA</td><td><input type="text" id="rank" placeholder="Add Rank"><input type="submit" value="Submit"></td><</tr>
          <tr><td>Jerry Smith</td><td>CS4820</td><td>PLA</td><td><input type="text" id="rank" placeholder="Add Rank"><input type="submit" value="Submit"></td></tr>
          <tr><td>Tiana </td><td>CS4820</td><td>TA</td><td><input type="text" id="rank" placeholder="Add Rank"><input type="submit" value="Submit"></td></tr>
        </tbody>
      </table>
    </div>
   </div>   <!-- end row -->
      
  <hr>            
      
  <div class="row">    
    <div class="col-md-4">
              
      <div class="panel panel-default" id="addcourse">
        <div class="panel-heading">
          <div class="panel-title">
            <i class="glyphicon glyphicon-wrench pull-right"></i>
            <h4>Add Courses</h4>
          </div>
        </div>
        <div class="panel-body">
          
          <form class="form form-vertical">
            <div class="control-group">
              <label>Courses Name</label>
              <div class="controls">
                <input type="text" class="form-control" placeholder="Enter Course Name">
              </div>
            </div>      
            <div class="control-group">
              <label>Instructor Name</label>
              <div class="controls">
                <input type="text" class="form-control" placeholder="Enter Instructor Name">
              </div>
            </div>      
            
                
            <div class="control-group">
              <label></label>
              <div class="controls">
                <button type="submit" class="btn btn-primary">
                  Add Course
                </button>
              </div>
            </div>   
            
          </form>
          
          
        </div><!--/panel content-->
      </div><!--/panel-->
      <hr>
              
      <div class="panel panel-default" id="deletecourse">
        <div class="panel-heading">
          <div class="panel-title">
            <i class="glyphicon glyphicon-wrench pull-right"></i>
            <h4>Delete Course</h4>
          </div>
        </div>
        <div class="panel-body">
          
          <form class="form form-vertical">
            <div class="control-group">
              <label>Course Name</label>
              <div class="controls">
                <input type="text" class="form-control" placeholder="Enter Course Name">
              </div>
            </div>      
            <div class="control-group">
              <label>Instructor Name</label>
              <div class="controls">
                <input type="text" class="form-control" placeholder="Enter Instructor Name">
              </div>
            </div>    
              
            <div class="control-group">
              <label></label>
              <div class="controls">
                <button type="submit" class="btn btn-primary">
                  Delete Course
                </button>
              </div>
            </div>   
            
          </form>
          
          
        </div><!--/panel content-->
      </div><!--/panel-->
      
      
    
    </div><!--/col-->
    
  </div><!--/row-->
  
  <div class="row">
    
    <div class="col-md-12">
      <hr>
		<h4><strong>Assign TA</strong></h4>  
         
    </div>
    <div class="col-md-12">
      
      <table class="table table-striped">
        <thead>
          <tr><th>Applicants</th><th>Course</th><th>TA/PLA</th><th>GPA</th><th>Offer Status</th><th>Assign</th></tr>
        </thead>
        <tbody>
          <tr><td>Sam Walker</td><td>CS4320</td><td>TA</td><td>3.7</td><td>Received</td><td><button class="btn btn-info btn-large" href="#">Assign</button></td></tr>
          <tr><td>Tory White</td><td>CS4320</td><td>TA</td><td>3.8</td><td>Received</td><td><button class="btn btn-info btn-large" href="#">Assign</button></td></tr>
          <tr><td>Tylor</td><td>CS4320</td><td>PLA</td><td>3.5</td><td>Rejected</td><td><button class="btn btn-info btn-large" href="#">Assign</button></td></tr>
          <tr><td>Jerry Smith</td><td>CS4820</td><td>PLA</td><td>3.6</td><td>Received</td><td><button class="btn btn-info btn-large" href="#">Assign</button></td></tr>
          <tr><td>Tiana </td><td>CS4820</td><td>TA</td><td>3.4</td><td>Rejected</td><td><button class="btn btn-info btn-large" href="#">Assign</button></td></tr>
        </tbody>
      </table>
    </div>
  </div>  
  <hr>              
  
  <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Please remember to <a href="#">Logout</a> for classified security.
  </div>
  
  
</div><!--/container-->
<!-- /Main -->


<footer class="text-center"> Copyright &copy; Software Engineering Group H, Spring 2015</footer>


<div class="modal" id="addWidgetModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add Widget</h4>
      </div>
      <div class="modal-body">
        <p>Add a widget stuff here..</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn">Close</a>
        <a href="#" class="btn btn-primary">Save changes</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dalog -->
</div><!-- /.modal -->



  
	<!-- script references -->
	
	</body>
</html>