<?php 
$status = session_status();
if($status == PHP_SESSION_NONE){
    //There is no active session
    session_start();
}
?>


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Admin Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/prof_styles.css')
		
    ?>
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
<!-- Header -->

<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  <div class="row">
	<div class="col-sm-3">
      <!-- left -->
      <h3><i class="glyphicon glyphicon-briefcase"></i> Toolbox</h3>
      
      <ul class="nav nav-stacked">
		<li><a href="#rankta"> Rank TA</a></li>
        <li><a href="#addcourse"> Add Courses</a></li>
        <li><a href="#deletecourse"> Delete Courses</a></li>
        <li><a href="javascript:;"> Assign TA</a></li>
      </ul>
      
      <hr>
      
  	</div><!-- /span-3 -->
    
    <div class="col-md-12" style="margin-top: 40px;">
       <div class="well" style="height:300px;">
            <h3>Search for an Applicant</h3>
            <form id='search' action='' method='post' accept-charset='UTF-8'>
                <input type="radio" name="choice" id="pawprint" value="pawprint">Search by PawPrint
                <br>
                <input type="radio" name="choice" id="name" value="name">Search by Applicant Name
                <br>
                <input type="text" name="input">
                <input type='submit' name='submit' value='Submit'>
            </form>
            <?php 
            if(isset($_POST['submit'])){
                include 'php/functions.php';
                include 'php/DB_Search.php';
                $type = $_POST['choice'];
                $conn = db_connect();
                $arr = search($conn, $_POST['input'], $type);
              
                if($arr != NULL){
             ?>
                        
                           <table class="table table-striped">
                                <thead>
                                  <tr><th>SSO</th><th>First Name</th><th>Last Name</th><th>GPA</th><th>E-mail</th><th>Ranking</th><th>Add/Change Rank</th></tr>
                                </thead>
                                <tbody>
                                <?php 
                                foreach ($arr as $t){
                                $t = json_decode($t, TRUE);
                                ?>

                                  <tr><form action="" method="POST">
                                    <td>
                                        <input type="hidden" name="test" value="<? echo $t['sso']?>">
                                            <? echo $t['sso'];?>
                                   </td>
                                   <td><? echo $t['fname']; ?>
                                   </td>
                                   <td><? echo $t['lname']; ?></td>
                                   <td><? echo $t['gpa']; ?></td>
                                   <td><? echo $t['email']; ?><td><? echo $t['ranking']; ?></td>
                                   <td>
                                   <input type="text" name="rank" placeholder="Add Rank">
                                   <input type="submit" name="submit2" value="Submit">
                                   </td> </form>
                                   </tr>

                                  <? 
                                }
                                
                                ?>
                                </tbody>
                              </table>
                          
          <?php }
          
                           else {
                               echo "no results found";
                               echo "<br>";
                           }         
            }

            if(isset($_POST['submit2'])){
                include 'php/rank.php';
                //echo "it's working";
                //echo $_POST['test'];
                //echo (int)$_POST['rank'];
            
                 
            
                addRank($_POST['test'], (int)$_POST['rank']);
            }
                          
                            
                                    
            include "test2.php";    
              
                
                ?>
       </div>
     </div>
    
  </div><!--/row-->
  <!-- /upper section -->
  
  
  <!-- lower section -->
  <hr>            
      
  <div class="row">    
    <div class="col-md-4">
              
      <div class="panel panel-default" id="addcourse">
        <div class="panel-heading">
          <div class="panel-title">
            <i class="glyphicon glyphicon-wrench pull-right"></i>
            <h4>Add/Delete Courses</h4>
          </div>
        </div>
        <div class="panel-body">
          
          <form class="form form-vertical" action="" method="POST">
            <div class="control-group">
              <label>Course ID</label>
              <div class="controls">
                <input type="text" class="form-control" name="courseID" placeholder="Enter Course ID (ex: CMP_SC 3050)">
              </div>
            </div>   
            <br>
            <div class="control-group">
              <label>Course Section</label>
              <div class="controls">
                <input type="text" class="form-control" name="section" placeholder="Enter Course ID (ex: CMP_SC 3050)">
              </div>
            </div>
            <br>   
            <div class="control-group">
              <label>Positions Available</label>
              <div class="controls">
                <input type="text" class="form-control" name="position" placeholder="Enter Number of Positions Available">
              </div>
            </div>      
            
            <br>    
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn btn-primary" name="addCourse">Add Course</button>
                <button type="submit" class="btn btn-danger" name="delCourse">Delete Course</button>
              </div>
            </div>   
            
          </form>
          <?php 
          include 'php/add_course.php';
          include 'php/delete_course.php';
          if(isset($_POST['addCourse'])){
              addCourse($_POST['courseID'], $_POST['section'], $_POST['position']);
          }
          if (isset($_POST['delCourse'])){
              deleteCourse($_POST['courseID'], $_POST['section']);
          }
          ?>
          
          
        </div><!--/panel content-->
      </div><!--/panel-->
      <hr>
              
      <div class="panel panel-default" id="deletecourse">
        <div class="panel-heading">
          <div class="panel-title">
            <i class="glyphicon glyphicon-wrench pull-right"></i>
            <h4>Add/Delete Instructor</h4>
          </div>
        </div>
        <div class="panel-body">
          
          <form class="form form-vertical" action="" method="POST">
            <div class="control-group">
              <label>Instructor SSO</label>
              <div class="controls">
                <input type="text" class="form-control" name="sso" placeholder="Enter Instructor SSO">
              </div>
            </div>
            <br>
            <div class="control-group">
              <label>Instructor First Name</label>
              <div class="controls">
                <input type="text" class="form-control" name="fname" placeholder="Enter Instructor First Name">
              </div>
            </div>
            <br>
            <div class="control-group">
              <label>Instructor Last Name</label>
              <div class="controls">
                <input type="text" class="form-control" name="lname" placeholder="Enter Instructor Last Name">
              </div>
            </div>       
            <br>  
            <div class="control-group">
              <!--  <label></label>-->
              <div class="controls">
                <button type="submit" class="btn btn-primary" name="addInst">Add Instructor</button>
                <button type="submit" class="btn btn-danger" name="delInst">Delete Instructor</button>
              </div>
            </div>   
            
          </form>
           <?php 
           include 'php/add_instructor.php';
           include 'php/delete_instructor.php';
          if(isset($_POST['addInst'])){
              addInstructor($_POST['sso'], $_POST['fname'], $_POST['lname']);
          }
          if (isset($_POST['delInst'])){
              deleteInstructor($_POST['sso']);
          }
          ?>
          
          
        </div><!--/panel content-->
      </div><!--/panel-->
      
      
    
    </div><!--/col-->
    
  </div><!--/row-->
  
  <div class="panel panel-default" style="margin-top: 400px; height:300px;">
        <div class="panel-heading"><h4 style="text-align: left;">Assign Applicants</h4></div>
            <?php 
            if(isset($_SESSION['username'])){
            include 'php/functions.php';
            $db = db_connect();
                if (!$db) {
                echo "Error.\n" . pg_last_error() . "\n";
                die; // kill the app if no connection
               }
               else {
                /*$res = pg_query($DBconn, "SELECT * FROM applicant_offer_received WHERE offer_accpeted = TRUE AND assigned_to_course IS NULL");
               ?>
                           <table class="table table-striped">
                               <thead>
                                   <tr><th>SSO</th><th>Course</th></tr>
                               </thead>
                               <tbody>
                                   <?php 
                                   while (($offer = pg_fetch_assoc($res)) != false) {    
                                   ?>
                                   <tr><td><? echo $offer['sso'];?></td><td><? echo $offer['course_id']; ?></td><td><button type="submit" class="btn btn-primary" name="acceptOffer">Accept</button></td><td><button type="submit" class="btn btn-primary" name="rejectOffer">Reject</button></td></tr>
                                   <?php } */
                                       echo "connection works.";
                } 
            }
            else {
                echo '<font color="red">' . "There are no currently no applicants that need to be assigned." . '</font><br>';
            }
                                   ?>
                               </tbody>
                           </table>
            
            
     </div>
    
  <hr>              
  
  
</div><!--/container-->
<!-- /Main -->


<footer class="text-center"> Copyright &copy; Software Engineering Group H, Spring 2015</footer>


<div class="modal" id="addWidgetModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add Widget</h4>
      </div>
      <div class="modal-body">
        <p>Add a widget stuff here..</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn">Close</a>
        <a href="#" class="btn btn-primary">Save changes</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dalog -->
</div><!-- /.modal -->



  
	<!-- script references -->
	
	</body>
</html>
