<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Homepage\Module'                        => __DIR__ . '/Module.php',
    'Homepage\Controller\HomepageController' => __DIR__ . '/src/Homepage/Controller/HomepageController.php',
    'HomepageTest\Framework\TestCase'        => __DIR__ . '/tests/Homepage/Framework/TestCase.php',
    'HomepageTest\SampleTest'                => __DIR__ . '/tests/Homepage/SampleTest.php',
);
