<?php 
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SWE Web App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))                        
                        ->prependStylesheet($this->basePath() . '/css/one-page-wonder.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            
        ; ?>
        

        <script>
        $.ajax({
            type: "POST",
            url: "../checkstatus.php",
            success: function(data){
                console.log(data);
                if(data=="instructor"){
                	$("li.ins").show();
                  	 $("li.stu").hide();
                  	 $("li.adm").hide();
                  	 $("li.log").hide();
                 }
                 
                 else if(data=="applicant"){
                	 $("li.ins").hide();
                	 $("li.stu").show();
                	 $("li.adm").hide();
                	 $("li.log").hide();
                 }
                 else if(data=="admin"){
                	 $("li.ins").hide();
                	 $("li.stu").hide();
                	 $("li.adm").show();
                	 $("li.log").hide();
                 }
                 else if(data=="new"){
                	 $("li.ins").hide();
                	 $("li.stu").show();
                	 $("li.adm").hide();
                	 $("li.log").hide();
                 }
                 else{
                	 $("li.ins").hide();
                	 $("li.stu").hide();
                	 $("li.adm").hide();
                	 $("li.log").show();
                 }
                
                 
            }
        
            });
        </script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top navbars" role="navigation">
		<img id="images" src="http://web.missouri.edu/~sykutam/images/mizzou_logo.gif" alt="tigermark" href="http://missouri.edu/">
        <div class="container" id="contain">
            <!-- Brand and toggle get grouped for better mobile display -->
			
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				
            
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/swespring2015">Home</a>
                    </li>
                    <li class="log">
                        <a href="login">Login</a>
                    </li>
                    <li class="stu">
                        <a href="test">Start Application</a>
                    </li>
                    <li class="stu">
                        <a href="studentpage">Student page</a>
                    </li>
                    <li class="ins">
                        <a href="professorpage">Professor page</a>
                    </li>
                    <li class="ins">
                        <a href="comments">View Comments page</a>
                    </li>
                    <li class="adm">
                        <a href="admin">Admin Page</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
					<a class="dropdown-toggle" role="button" data-toggle="dropdown">
						<i class="glyphicon glyphicon-user"></i> 
						<?php 
						if(isset($_SESSION['username'])){
    						echo $_SESSION["username"];
						}
						else {
						    echo "Login";
						}
						?> 
						<span class="caret"></span></a>
					<ul id="g-account-menu" class="dropdown-menu" role="menu">
						<li><a href='../logout.php'><i class="glyphicon glyphicon-lock"></i>Logout</a></li>
					</ul>
				</ul>
				
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
           <!--       <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>-->
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
