 <!-- Full Width Image Header -->
    <header class="header-image">
		
        <div class="headline">
            <div class="container">
                <h2>TA/PLA APPLICATION</h2>
                <h2><small>COMPUTER SCIENCE DEPARTMENT</small></h2>
            </div>
        </div>
    </header>

    <!-- Page Content -->
	<div id="bground">
    <div class="container">

        <hr class="featurette-divider">

        <!-- First Featurette -->
        <div class="featurette" id="about">
			<div class="login">
				<div class="trumanface"></div>
				<div class="trumanpaws"></div>
				<div class="text">
					<h2>Want to Apply?</h2>
					<h3>Start Here And Get Your Application Form</h3>
					<button class="btn loginbutton" onclick="http://swespring2015-grouph.rhcloud.com/swespring2015/login">Login</button>
				</div>
			</div>
            <h2 class="featurette-heading">REQUIREMENT               
                <div class="text-muted"><u>Deadline</u>: Friday, April 3nd</div>
            </h2>
            <div class="lead">
				<li>Please submit the Application Form along with a current resume before deadline.</li>
				<li>New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO
(Graduate Assistant Teaching Orientation).</li>
				<li>Prior to becoming a TA, any ITA (International Teaching Assistant) who received their primary and
secondary education in a country where English is not the principal language <u>are required by law to
be assessed for English proficiency (SPEAK test).</u></li>
			</div>
        </div>



        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Software Engineering Group H, Spring 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
	</div>

    <!-- jQuery -->

    <!-- Bootstrap Core JavaScript -->
	