<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Test\Module'                        => __DIR__ . '/Module.php',
    'Test\Controller\TestController' => __DIR__ . '/src/Test/Controller/TestController.php',
    'TestTest\Framework\TestCase'        => __DIR__ . '/tests/Test/Framework/TestCase.php',
    'TestTest\SampleTest'                => __DIR__ . '/tests/Test/SampleTest.php',
);
