<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Professorpage\Module'                        => __DIR__ . '/Module.php',
    'Professorpage\Controller\ProfessorpageController' => __DIR__ . '/src/Professorpage/Controller/ProfessorpageController.php',
    'ProfessorpageTest\Framework\TestCase'        => __DIR__ . '/tests/Professorpage/Framework/TestCase.php',
    'ProfessorpageTest\SampleTest'                => __DIR__ . '/tests/Professorpage/SampleTest.php',
);
