<?php 
$status = session_status();
if($status == PHP_SESSION_NONE){
    //There is no active session
    session_start();
}
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Faculty Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/prof_styles.css')?>
        
		<style>
		td {
			text-align:center;
		}
		th {
			text-align:center;
		}
		tbody {
			width:100%;
		}
		</style>
	</head>
	<script type="text/javascript">
	   jQuery(document).ready(function() {
	   /*
	   function buildSession(){
		   var sso = document.getElementById('bSession').value
		   console.dir(sso);
		   '<%Session["sso"] = "' + sso + '"; %>';
		}
	   */
		   function save_var() {
			    var stu_sso = document.getElementById('bSession').value
		        
		        alert(stu_sso);
		        jQuery.ajax({
		          type: 'post',
		          url: 'php/save_var.php',
		          data: stu_sso,
		          complete: function(){
		              jQuery("#bSession").submit(); //submit the form after ajax completes
		          }
		        });
		        return false; //stop the form from initially submitting
		      }
		    });
	</script>
	<body>
<!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button> 
      <form id='logout' action='' method='post' accept-charset='UTF-8' style="padding-top: 200px;">
      <input type='submit' name='logout' value='Logout' /> 
      </form>
      <?php 
        if(isset($_POST['logout'])){
            session_destroy();
        }
      ?>
      
    </div>
    
  </div><!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  
    <div class="col-md-12" style="margin-top: 40px;">
       <div class="well" style="height:300px;">
            <h3>Search for an Applicant</h3>
            <form id='search' action='' method='post' accept-charset='UTF-8'>
                <input type="radio" name="choice" id="pawprint" value="pawprint">Search by PawPrint
                <br>
                <input type="radio" name="choice" id="name" value="name">Search by Applicant Name
                <br>
                <input type="text" name="input">
                <input type='submit' name='submit' value='Submit'>
            </form>
            <?php 
            if(isset($_POST['submit'])){
                include 'php/functions.php';
                include 'php/DB_Search.php';
                $type = $_POST['choice'];
                $conn = db_connect();
                $arr = search($conn, $_POST['input'], $type);
            
                if($arr != NULL){
                    ?>
                                    <form action="rank.php" method="POST">
                                       <table class="table table-striped">
                                            <thead>
                                              <tr><th>SSO</th><th>First Name</th><th>Last Name</th><th>GPA</th><th>E-mail</th><th>Ranking</th><th>Add/Change Rank</th></tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            foreach ($arr as $t){
                                            $t = json_decode($t, TRUE);
                                            ?>
                                              <tr><td><? echo $t['sso'];?></td><td><? echo $t['fname']; ?></td><td><? echo $t['lname']; ?></td><td><? echo $t['gpa']; ?></td><td><? echo $t['email']; ?><td><? echo $t['ranking']; ?></td><td><input type="text" id="rank" placeholder="Add Rank"><input type="submit" value="Submit"></td></tr>
                                            <? } ?>
                                            </tbody>
                                          </table>
                                       </form>
                                       <?php 
                                            }
                                            else {
                                                echo "no results found";
                                            }
                                        }
                           
                            ?>
       </div>
     </div>
     <hr>
     <hr>
     <hr>
     <hr>
     <div class="panel panel-default" style="margin-top: 400px; height:300px;">
        <div class="panel-heading"><h4 style="text-align: left;">Courses You Are teaching this Semester</h4></div>
            <?php 
            if(isset($_SESSION['username'])){
            $connectionString = "user=admin1xtduwt password=zVd4BSi4JdIJ host=127.13.165.130 dbname=ta_application";
            $DBconn = pg_connect($connectionString);
                if (!$DBconn) {
                echo "Error.\n" . pg_last_error() . "\n";
                die; // kill the app if no connection
               }
               else 
                $result = pg_query($DBconn, "SELECT course_id, section FROM instructor_teaches WHERE instructor_sso='".$_SESSION['username']."';");
               ?>
                           <table class="table table-striped">
                               <thead>
                                   <tr><th>Course ID</th><th>Section</th></tr>
                               </thead>
                               <tbody>
                                   <?php 
                                   while (($row = pg_fetch_assoc($result)) != false) {    
                                   ?>
                                   <tr><td><? echo $row['course_id'];?></td><td><? echo $row['section']; ?></td></tr>
                                   <?php } 
            }
            else {
                echo '<font color="red">' . "Please login to see the courses you are teaching this semester." . '</font><br>';
            }
                                   ?>
                               </tbody>
                           </table>
            
            
     </div>                 
 
    <div class="panel panel-default">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped">
                    <thead>
                        <tr><th>Applicant Name</th><th>Wish List Course</th><th>TA/PLA</th><th>GPA</th><th>Grade Recieved</th><th>Make Offer</th><th>Add Comments</th></tr>
                    </thead> 
                    <tbody>
                        <?php
                        if(isset($_SESSION['username'])){
                            //php script to find applicants
                            require 'php/functions.php';
                            
                            $conn = db_connect();
                            if($conn) {
                                $inst_sso = $_SESSION['username'];
                                //query the DB to find what courses the instructor teaches
                               
                                $results = pg_prepare($conn,"find_applicants",'SELECT applicant.sso, applicant.fname, applicant.lname, applicant.gpa, applicant_wish_course.grade_received, 
                                        applicant_wish_course.course_id AS course FROM applicant
                                        INNER JOIN applicant_wish_course
                                        ON applicant.sso = applicant_wish_course.sso
                                        WHERE applicant_wish_course.course_id IN (
                                        	SELECT course_id FROM instructor_teaches
                                        	WHERE instructor_sso like $1
                                        )');
                                $results = pg_execute($conn,"find_applicants",array($inst_sso));

                                if($results) {
                                    $qry = "SELECT * FROM applicant_is_a_ugrad WHERE sso like $1";
                                    $is_ugrad = pg_prepare($conn,"ugrad_search",$qry);
                                    while($row =  pg_fetch_array($results, null, PGSQL_ASSOC)) {
                                        ?><tr><td><?echo $row['fname'].' '. $row['lname']?></td><td><?echo $row['course']?></td><td><?php 
                                        $is_ugrad = pg_execute($conn,"ugrad_search",array($row['sso']));
                                        $is_ugrad =pg_fetch_array($is_ugrad,null,PGSQL_ASSOC);
                                        if($is_ugrad['program']!=null){
                                            echo 'PLA';
                                        }
                                        else {
                                            
                                            echo 'TA';
                                        } ?></td><td><?echo $row['gpa']?></td><td><?echo $row['grade_received']?></td><td><button type="button" class="btn btn-primary">Offer</button></td><td><form action="comments" method="POST"><button type="submit" class="btn btn-primary" id="bSession" name="sso" value="<?echo $row['sso']?>" onclick="buildSession()">Add/View Comments</button></form></td><tr><?

                                    }
                                    
                                }
                                
                            }
                            else {
                                echo '<font color="red">' . "Please login to see applicants interested in teaching your course." . '</font><br>';
                            }
                            
                        }
                        
                        ?>
                    </tbody>
                    
                </table>
          </div>
       </div>
   </div>
      
      <hr>    
      </div>        
     
<!-- /Main -->


<footer class="text-center"> Copyright &copy; Software Engineering Group H, Spring 201</footer>




  
	<!-- script references 
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>-->
	</body>
</html>

