<?php 
$status = session_status();
if($status == PHP_SESSION_NONE){
    //There is no active session
    session_start();
}
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Faculty Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/prof_styles.css')?>
        
		<style>
		td {
			text-align:center;
		}
		th {
			text-align:center;
		}
		tbody {
			width:100%;
		}
		</style>
	</head>
	<body>
<!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button> 
      <?php 
        if(isset($_SESSION['username'])){
            echo "Welcome," . $_SESSION["username"];
        }
        else {
            echo "";
        }
      ?>
      <form id='logout' action='' method='post' accept-charset='UTF-8' style="padding-top: 200px;">
      <input type='submit' name='logout' value='Logout' /> 
      </form>
      <?php 
        if(isset($_POST['logout'])){
            session_destroy();
        }
      ?>
      
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
            <i class="glyphicon glyphicon-user"></i> Grant Scott <span class="caret"></span></a>
          <ul id="g-account-menu" class="dropdown-menu" role="menu">
            <li><a href="#">My Profile</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  
    <div class="col-md-9" style="margin-bottom: 20px;">
       <div class="well">
            <h3>Search for an Applicant</h3>
            <form>
                <input type="radio" name="choice" value="pawprint">Search by PawPrint
                <br>
                <input type="radio" name="choice" value="name">Search by Applicant Name
                <br>
                <input type="text" name="input">
                <input type="submit" value="Submit">
            </form>
            <br>
            <br>
            <br>
            <br>
            <br>
       </div>
     </div>
     <hr>
     <hr>
     <hr>
     <hr>
     <div class="panel panel-default" style="margin-top: 200px; height:300px;">
        <div class="panel-heading"><h4 style="text-align: left;">Courses Taught this Semester</h4></div>
            <?php 
            $connectionString = "user=admin1xtduwt password=zVd4BSi4JdIJ host=127.13.165.130 dbname=ta_application";
            $DBconn = pg_connect($connectionString);
                if (!$DBconn) {
                echo "Error.\n" . pg_last_error() . "\n";
                die; // kill the app if no connection
               }
            else $query = "SELECT course_id, slots_available FROM course;";
            $result = pg_query($DBconn, $query);
        while (($row = pg_fetch_assoc($result)) != false) {
        
        print $row['course_id'] . "<br>";
	    print $row['slots_available'] . "<br>";
}            
            
            ?>
     </div>                 
 
    <div class="panel panel-default">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped">
                    <thead>
                        <tr><th>Applicant Name</th><th>Wish List Course</th><th>TA/PLA</th><th>GPA</th><th>Grade Recieved</th><th>Make Offer</th><th>Add Comments</th></tr>
                    </thead>
                    <!--
                    <tbody>
                      <tr><td>Sam Walker</td><td>CS4320</td><td>TA</td><td>4.0</td><td>A</td><td><button type="button" class="btn btn-primary">Offer</button></td><td><form action="comments" method="POST"><button type="submit" class="btn btn-primary">Add/View Comments</button></form></td></tr>
                      <tr><td>Tory White</td><td>CS4320</td><td>PLA</td><td>3.7</td><td>A</td><td><button type="button" class="btn btn-primary">Offer</button></td><td><form action="comments" method="POST"><button type="submit" class="btn btn-primary">Add/View Comments</button></form></td></tr>
                      <tr><td>Tylor Jones</td><td>CS4320</td><td>TA</td><td>3.4</td><td>B</td><td><button type="button" class="btn btn-primary">Offer</button></td><td><form action="comments" method="POST"><button type="submit" class="btn btn-primary">Add/View Comments</button></form></td></tr>
                      <tr><td>Jerry Smith</td><td>CS4320</td><td>PLA</td><td>3.6</td><td>A</td><td><button type="button" class="btn btn-primary">Offer</button></td><td><form action="comments" method="POST"><button type="button" class="btn btn-primary">Add/View Comments</button></form></td></tr>
                      <tr><td>Mary Test</td><td>CS4320</td><td>TA</td><td>3.7</td><td>B</td><td><button type="button" class="btn btn-primary">Offer</button></td><td><form action="comments" method="POST"><button type="button" class="btn btn-primary">Add/View Comments</button></form></td></tr>
                    </tbody>
                    -->
                    
                    <tbody>
                        <?php
                            //php script to find applicants
                            require 'php/functions.php';
                            
                            $conn = db_connect();
                            if($conn) {
                                $inst_sso = $_SESSION['username'];
                                //query the DB to find what courses the instructor teaches
                               
                                $results = pg_prepare($conn,"find_applicants",'SELECT applicant.sso, applicant.fname, applicant.lname, applicant.gpa, applicant_wish_course.grade_received, 
                                        applicant_wish_course.course_id AS course FROM applicant
                                        INNER JOIN applicant_wish_course
                                        ON applicant.sso = applicant_wish_course.sso
                                        WHERE applicant_wish_course.course_id IN (
                                        	SELECT course_id FROM instructor_teaches
                                        	WHERE instructor_sso like $1
                                        )');
                                $results = pg_execute($conn,"find_applicants",array($inst_sso));
                                if($results) {
                                    while($row =  pg_fetch_array($results, null, PGSQL_ASSOC)) {
                                        ?><tr><td><?echo $row['fname'].' '. $row['lname']?></td><td><?echo $row['course']?></td><td></td><td><?echo $row['gpa']?></td><td><?echo $row['grade_received']?></td><td><button type="button" class="btn btn-primary">Offer</button></td><td><form action="comments" method="POST"><button type="submit" class="btn btn-primary" id="<?echo $row['sso']?>">Add/View Comments</button></form></td><tr><?
                                    }
                                }
                            }
                            
                        ?>
                    </tbody>
                    
                </table>
          </div>
       </div>
   </div>
      
      <hr>    
      </div>        
     
<!-- /Main -->


<footer class="text-center"> Copyright &copy; Software Engineering Group H, Spring 201</footer>




  
	<!-- script references 
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>-->
	</body>
</html>

