<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Faculty Page</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/prof_styles.css')
    ?>
        
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
<!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button>
      <a class="navbar-brand" href="#">TA/PLA Application For Professor</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
            <i class="glyphicon glyphicon-user"></i> Grant Scott <span class="caret"></span></a>
          <ul id="g-account-menu" class="dropdown-menu" role="menu">
            <li><a href="#">My Profile</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  <div class="row">
	<div class="col-sm-3">
      <!-- left -->
      <h3><i class="glyphicon glyphicon-briefcase"></i> Toolbox</h3>
      <hr>
      
      <ul class="nav nav-stacked">
		<li><a href="javascript:;"> Personal Information</a></li>
        <li><a href="javascript:;"> Courses</a></li>
        <li><a href="javascript:;"> Applications</a></li>
        <li><a href="javascript:;"> Comments</a></li>
        <li><a href="javascript:;"> Request TA</a></li>
        <li><a href="javascript:;"> Tools</a></li>
      </ul>
      
      <hr>
      
  	</div><!-- /span-3 -->
    <div class="col-sm-9">
      	
      <!-- column 2 -->	
       <h3><i class="glyphicon glyphicon-dashboard"></i> Dashboard</h3>  
            
       <hr>
      
	   <div class="row">
            <!-- center left-->	
         	<div class="col-md-7">
			  <div class="well">New Application Forms <span class="badge pull-right">3</span></div>
              
              <hr>
              
              <div class="panel panel-default">
                  <div class="panel-heading"><h4>Processing Status</h4></div>
                  <div class="panel-body">
                    <div>
						
					</div>
                    <small>Complete Assign</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100" style="width: 72%">
                        <span class="sr-only">72% Complete</span>
                      </div>
                    </div>
                    <small>In Progress</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                    <small>Still Need TA/PLA</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>

                  </div><!--/panel-body-->
              </div><!--/panel-->                     
              
          	</div><!--/col-->
         
            <!--center-right-->
        	
     
       </div><!--/row-->
  	</div><!--/col-span-9-->
    
  </div><!--/row-->
  <!-- /upper section -->
  
  <!-- lower section -->
  <div class="row">
    
    <div class="col-md-12">
      <hr>
      <a href="#"><strong><i class="glyphicon glyphicon-list-alt"></i> Application Forms</strong></a>  
      <hr>    
    </div>
    <div class="col-md-8">
      
      <table class="table table-striped">
        <thead>
          <tr><th>Applicants</th><th>Course</th><th>TA/PLA</th><th>Comments and Notes</th></tr>
        </thead>
        <tbody>
          <tr><td>Sam Walker</td><td>CS4320</td><td>TA</td><td>Sam sapien massa, aliquam in cursus ut, ullamcorper in tortor. 
          Aliquam mauris arcu, tristique a lobortis vitae, condimentum feugiat justo.</td></tr>
          <tr><td>Tory White</td><td>CS4320</td><td>TA</td><td><a href="#">Add Comments</a></td></tr>
          <tr><td>Tylor </td><td>CS4320</td><td>PLA</td><td><a href="#">Add Comments</a></td></tr>
          <tr><td>Jerry Smith</td><td>CS4820</td><td>PLA</td><td>Forfoot aliquam in cursus ut, ullamcorper in tortor. 
          Okma mauris arcu, tristique a lobortis vitae, condimentum feugiat justo.</td></tr>
          <tr><td>Tiana </td><td>CS4820</td><td>TA</td><td>Mikel sapien massa, aliquam in cursus ut, ullamcorper in tortor. 
          Maliquam mauris arcu, tristique a lobortis vitae, condimentum feugiat justo.</td></tr>
        </tbody>
      </table>
      
      <hr>              
      
      
      
      <hr>
      
      <div class="panel panel-default">
        <div class="panel-heading"><h4>Show TA/PLA Requests</h4></div>
        <div class="panel-body">
          <div class="list-group">
		    
			    <a href="#" class="list-group-item active">Need Sam Walker to be a TA of CS4320</a>
				<a href="#" class="list-group-item">Need Jerry Smith to be a PLA of CS4820</a>
			
			
          </div>
        </div>
      </div>
      
      <hr>
      
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Please remember to <a href="#">Logout</a> for classified security.
      </div>

    
    </div>
    <div class="col-md-4">
      
      
      
      <hr>
              
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title">
            <i class="glyphicon glyphicon-wrench pull-right"></i>
            <h4>Send Request</h4>
          </div>
        </div>
        <div class="panel-body">
          
          <form class="form form-vertical">
            <div class="control-group">
              <label>Applicants Name</label>
              <div class="controls">
                <input type="text" class="form-control" placeholder="Enter Name">
              </div>
            </div>      
             
            <div class="control-group">
              <label>Details</label>
              <div class="controls">
                <textarea class="form-control"></textarea>
              </div>
            </div> 
            <div class="control-group">
              <label>Select Course</label>
              <div class="controls">
                <select class="form-control"><option>CS4320</option><option>CS4820</option></select>
              </div>
            </div>    
            <div class="control-group">
              <label></label>
              <div class="controls">
                <button type="submit" class="btn btn-primary">
                  Send to Admin
                </button>
              </div>
            </div>   
            
          </form>
          
          
        </div><!--/panel content-->
      </div><!--/panel-->
      
      
    
    </div><!--/col-->
    
  </div><!--/row-->
  
</div><!--/container-->
<!-- /Main -->


<footer class="text-center"> Copyright &copy; Software Engineering Group H, Spring 2015</a></footer>


<div class="modal" id="addWidgetModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add Widget</h4>
      </div>
      <div class="modal-body">
        <p>Add a widget stuff here..</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn">Close</a>
        <a href="#" class="btn btn-primary">Save changes</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dalog -->
</div><!-- /.modal -->



  
	<!-- script references 
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>-->
	</body>
</html>