<!DOCTYPE html>
<html>
<head>
<title>404 - Page Not Found</title>
<style>
body {
}

h1{
font-size: 150pt;
font-family: verdana;
margin-top: 0px;
color: red;
}

h2 {
font-size: 48pt;
}

.wrapper {
background-color: lightblue;
height: 600px;
width: 100%;
border-radius: 20pt;
}

.404 {
}

.broke {
position: fixed;
top: 20px;
left: 420px;
}

.sorry {
position: fixed;
left: 545px;
top: 115px;
font-size: 15pt;
}

</style>
</head>
<body>
<div class="wrapper">
<div class="404">
<h1>404</h1>
</div>
<div class="broke">
<h2>Uh Oh! I Think You Broke It.</h2>
</div>
<div class="sorry">
<h3>Sorry, the page you are looking for cannot be found</h3>
</div>


</body>
</html>
