<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Applicationstatus\Module'                        => __DIR__ . '/Module.php',
    'Applicationstatus\Controller\ApplicationstatusController' => __DIR__ . '/src/Applicationstatus/Controller/ApplicationstatusController.php',
    'ApplicationstatusTest\Framework\TestCase'        => __DIR__ . '/tests/Applicationstatus/Framework/TestCase.php',
    'ApplicationstatusTest\SampleTest'                => __DIR__ . '/tests/Applicationstatus/SampleTest.php',
);
