<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Error\Module'                        => __DIR__ . '/Module.php',
    'Error\Controller\ErrorController' => __DIR__ . '/src/Error/Controller/ErrorController.php',
    'ErrorTest\Framework\TestCase'        => __DIR__ . '/tests/Error/Framework/TestCase.php',
    'ErrorTest\SampleTest'                => __DIR__ . '/tests/Error/SampleTest.php',
);
