<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Studentpage\Module'                        => __DIR__ . '/Module.php',
    'Studentpage\Controller\StudentpageController' => __DIR__ . '/src/Studentpage/Controller/StudentpageController.php',
    'StudentpageTest\Framework\TestCase'        => __DIR__ . '/tests/Studentpage/Framework/TestCase.php',
    'StudentpageTest\SampleTest'                => __DIR__ . '/tests/Studentpage/SampleTest.php',
);
