<!-- 

<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="applicationform" target="_blank"><?php echo $this->translate('application form!') ?> &raquo;</a></p>
    <p><a class="btn btn-success btn-lg" href="homepage" target="_blank"><?php echo $this->translate('homepage') ?> &raquo;</a></p>
    
    </div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
-->



 <!-- Full Width Image Header -->
    <header class="header-image">
		
        <div class="headline">
            <div class="container">
                <h2>TA/PLA APPLICATION</h2>
                <h2><small>COMPUTER SCIENCE DEPARTMENT</small></h2>
            </div>
        </div>
    </header>

    <!-- Page Content -->
	<div id="bground">
    <div class="container">

        <hr class="featurette-divider">

        <!-- First Featurette -->
        <div class="featurette" id="about">
			<div class="login">
				<div class="trumanface"></div>
				<div class="trumanpaws"></div>
				<div class="text">
					<h2>Want to Apply?</h2>
					<h3>Start Here And Get Your Application Form</h3>
					<button class="btn loginbutton" onclick="\login">Login</button>
				</div>
			</div>
            <h2 class="featurette-heading">REQUIREMENT               
                <div class="text-muted"><u>Deadline</u>: Friday, April 3nd</div>
            </h2>
            <div class="lead">
				<li>Please submit the Application Form along with a current resume before deadline.</li>
				<li>New TAs, ITAs, and PLAs who have received an appointment, are required to participate in the GATO
(Graduate Assistant Teaching Orientation).</li>
				<li>Prior to becoming a TA, any ITA (International Teaching Assistant) who received their primary and
secondary education in a country where English is not the principal language <u>are required by law to
be assessed for English proficiency (SPEAK test).</u></li>
			</div>
        </div>



        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Software Engineering Group H, Spring 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
	</div>

    <!-- jQuery -->

    <!-- Bootstrap Core JavaScript -->
	
